spring:
  kafka:
    host: 10.202.162.9

#数据库连接配置
  dataSource:
    url: jdbc:oracle:thin:@ordb.dev.bl.com:1521:devdb  
    username: product  
    password: product_2316   
    poolName: formal_source
    driver-class-name: oracle.jdbc.driver.OracleDriver
    maxActive: 30
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    connectionTimeout: 10000

#rabbitmq连接配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${spring.cloud.config.uri}/eureka/
    healthcheck:
      enabled: true
  #instance:
    #lease-renewal-interval-in-seconds: 30
    #lease-expiration-duration-in-seconds: 10
    
#关闭内置接口请求安全校验
management:
  security:
    enabled: false
