#日志配置
logging:
  file: D:\config-client.log
  level: 
    root: WARN
    com.bailian: INFO
    org.springframework: INFO
    
#数据库配置
spring:
  dataSource:
    url: jdbc:oracle:thin:@ordb.dev.bl.com:1521:devdb  
    username: product  
    password: product_2316   
    driver-class-name: oracle.jdbc.driver.OracleDriver
    maxActive: 30
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    connectionTimeout: 10000
    
#kafka消息中间件(消费者)
  kafka:
    consumer:
      servers: 10.202.161.190:9092,10.202.161.191:9092,10.202.161.192:9092
      enable:
        auto:
          commit: true
      session:
        timeout: 6000
      auto:
        commit:
          interval: 100
        offset:
          reset: latest
      concurrency: 10
      group:
        id: kafka-demo

#rabbitmq连接配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${spring.cloud.config.uri}/eureka/
    healthcheck:
      enabled: true
  #instance:
    #lease-renewal-interval-in-seconds: 30
    #lease-expiration-duration-in-seconds: 10
    
#关闭bus封装接口的请求安全校验
management:
  security:
    enabled: false
#关闭feign对熔断器的支持
feign: 
  hystrix:
    enabled: false
